Templating
Sage-Bionetworks-Workflows/cwl-tool-template pull request #27
Opened 2020-12-10 10:15 UTC by thomasyu888

2021-03-23 18:24 UTC, tthyer approved these changes
@thomasyu888 This looks good to me -- I'm eager to get templating into the tool
@BrunoGrandePhD Please review

2021-03-23 19:17 UTC, zaro0508 commented on .github/workflows/ci.yaml
> +          pipenv run utils/bump_cwl_version.py $tools_dir $new_version $templates_dir
to make it more generic how about passing in a json `input` or `data` dictionary here.  something like..
```
{
  "data": {
    "version": "1.0.0"
  }
}
```

then you can reference it with `{{ data.version }}` in your mustache templates.  that way you can pass in more than one piece of data.

2021-03-23 23:00 UTC, BrunoGrandePhD requested changes
I was hoping to test the CI workflow, but I haven't gotten `act` to work locally and I don't want to hold up this PR for that. It'll become clear if it works or not once it's merged. 

All I request is that the `echo_best_practices.cwl` file be restored to what I committed to the repository before it was mangled. I'll approve once that's done.

2021-03-24 10:42 UTC, thomasyu888 commented on Pipfile.lock
> +        "iniconfig": {
```suggestion
        "more-itertools": {
```

2021-03-24 10:42 UTC, thomasyu888 commented on Pipfile.lock
> +        "toml": {
```suggestion
        "wcwidth": {
```

2021-03-24 15:18 UTC, BrunoGrandePhD approved these changes
🚀

2021-07-20 22:41 UTC, merged